termite.cc
Regarding updating to vte 0.40.0, vte now makes the following assertion:
```
(termite:8742): Vte-CRITICAL **: vte_terminal_set_colors: assertion '(palette_size == 0) || (palette_size == 8) || (palette_size == 16) || (palette_size == 232) || (palette_size == 256)' failed
```
and colors will be basically broken without the following change.  I think this should have been 256 anyways.
=> Set color palette size to 256

.ycm_extra_conf.py
The dependency was changed in the Makefile but .ycm_extra_conf.py wasn't updated accordingly.
=> Specify proper vte version in .ycm_extra_conf.py

config, man/termite.config.5, termite.cc
added another table for keys modified by both CTRL and META.
One odd thing here is that neither semicolon `C-M-;` nor colon `C-M-S-;` work.
I don't know if there's a better way to write the `else if (CONDITION)` I added, like perhaps I should split the new table into two tables: one for CTRL-META-mask, the other for CTRL-META-SHIFT-mask.
=> Modify other keys

README.rst, man/termite.1, termite.cc
Reset the font size to the default startup value
by pressing '=' in selection mode.
Closes: #164
=> Reset font size to startup default using a keybinding

termite.cc
Remove the search_panel_info's panel, which was an alignment
widget for the entry widget. Since the entry widget can now
set alignment using it's margin properties.
Replace gtk_alignment_set_padding with gtk_widget_set_margin_*.
These changes make termite depend on GTK3 >= 3.14.
=> Resolve GTK3 deprecation warnings

termite.cc
The font_scale member of the struct config_info was not
initialized.
=> Resolve missing field 'font_scale' initializer

termite.cc
vte_terminal_match_check has been replaced by
vte_terminal_match_check_event which takes the GdkEvent
and does not need to be passed a row and col.
Seems the padding is also not required anymore somehow. don't really understand why, but url selection still looks good and works.
=> Replace deprecated vte_terminal_match_check

config, termite.cc
VTE 0.44.1 supports setting the foregorund color of
the cursor using vte_terminal_set_color_cursor_foreground
Closes: #284
=> Add support to set the foreground cursor color

termite.cc
GCC 6.1 warns about the comparison between an
long and double, cast the long to a double.
=> Resolve GCC 6.1 warning

termite.cc
`gdk_rgba_to_string` allocates and returns a `gchar*` but this gets lost because it is contained in a variable. I pulled out the method so we could free it after use.
=> termite.cc: pull out a method call into a variable so we can free it

termite.cc
When moving the cursor in selection mode disabling blinking
mode. This behaviour is smiliar to moving the cursor in vim.
Closes: #275
=> Disable blinking when moving cursor in selection mode

.ycm_extra_conf.py
The call to subprocess.check_output returns a bytes instead of a str
object if not called with universal_newlines=True which raises an
exception further on due to mixing of bytes and str.
=> Fix exception thrown in .ycm_extra_conf.py

termite.cc
`Ctrl-=` and `Ctrl-+` commands did not work on non-US like keyboard
layouts because `=` and `+` are produced differently in other layouts
e.g. `Shift` is required/not required respectively. The opposite of US
like layouts.
This patch fixes the issue by not checking if `Shift` is pressed/not
pressed when it's irrelevant to the command. Instead it uses the
`keyval` from GDK directly which has been transformed depending on
keyboard layout and pressed modifiers.
Fix #371
I have tested this on US and Danish keyboard layouts, but it would be nice if others could test as well, also to make sure I didn't break any other key combinations. @jelly @quasisphere @f-koehler @dmarcoux
Cheers!
=> Make key commands work on non-US keyboard layouts

termite.cc
vte3 0.46 introduced an assertion valid_color which checks if the alpha
channel is set. The alpha channel is actually not used in
vte_terminal_set_colors.
=> load_theme: set alpha to 0 of GdkRGBA

config
Document the cursor color and cursor_foreground behaviour with the
default termite configuration.
=> Document default color and cursor_foreground behavior

termite.cc
This reverts commit 305f5cb9381b28740797b646664f2d16ca1f33e8.
The old fix breaks it on US keyboards.  Instead, copy the case down to
be in both ifs.
=> Revert "non us fix" and fix it properly

termite.cc
Before this fix, in visual mode, `b` and `B` set the curser to the begin of a word + 1 character.
=> Bugfix for b and B in visual mode

README.rst
Add a section about copying terminfo to remote systems to hopefully stop
the pile of non-issues opened because of a missing terminfo file.
=> README: Add terminfo information

termite.cc
vte_terminal_match_add_gregex, vte_terminal_search_get_gregex and
vte_terminal_search_set_gregex are all deprecated and replaced with the
VTeRegex API which uses PCRE2.
Closes: #395
=> Replace deprecated gregex api

termite.cc
Handles invalid configuration format, such as:
```
garbage is garbage
```
=> Handle invalid configuration file format

termite.cc
the shell detection might fail with a strange message and to me it was unclear what the problem was. 
The error was something like cannot run "" .
I compiled termite on Ubuntu 16.04, and the user I have tested with did not have an entry for the shell in /etc/passwd. This can happen easily because the adduser command does not add the shell automatically (have not seens this on other Linux flavors so far). Ubuntu  sets the SHELL variable to an empty string. vte_get_user_shell behaves similarly.
I therefore added some simple checks, such that at least the /bin/sh should work.
=> improving shell detection

Makefile
hanetzer in #gentoo-chat on freenode reported errors like this when building
termite:
tic -x termite.terminfo -o /tmp/portage/x11-terms/termite-9999/image//usr/share/terminfo
tic: Too many file names.  Usage:
tic [-e names] [-o dir] [-R name] [-v[n]] [-V] [-w[n]] [-1aCDcfGgIKLNrsTtUx] source-file
Moving the input filename to the end of the tic invocation seems to resolve
this for them, but I am unable to reproduce the issue.
=> Fix order of arguments in tic command

README.rst, config, man/termite.config.5, termite.cc
Even in the keyboard-centric interface, scrollbar still have indicative purpose:
* indicate current position within scrollback buffer
* indicate total scrollback size relative to visible screen size
Following new options are valid:
```
scrollbar = off
scrollbar = left
scrollbar = right
```
-----
Also introduce add `.termite` GTK CSS class to allow padding (see `README.rst`) not just around VTE widget itself, but also scrollbar.
=> Add optional scrollbar

termite.cc
vte_terminal_hyperlink_check_event only matches explicit OSC 8 marked
hyperlinks, so we still need to fall back to the existing check_match
function for the vast majority of URLs to be clickable.
=> Need to fall back to check_match after hyperlink_check_event

termite.cc
Some background: I used to use rxvt-unicode and I have a few CLI commands set up in my window manager to float instead of tile when launched with `urxvt -e $COMMAND`. This was done by checking the X client's title, which I discovered is not set by termite when executing commands in this way.
In order to reproduce: try running `termite` and then running `top`, and compare with running `termite -e top`. In the first scenario the title is set to "top" by bash's escape wizardry, in the second scenario the title remains "termite".
This quick patch sets the title on startup when termite is executed with the `-e` flag, if and only if the title has not been set by the `-t` flag, and it respects any further title change signaled by `vte` after startup.
=> Set title to passed command when executing with -e

Makefile, termite.cc
This reverts commit 8dd8f55088081965a308ea104bf645a877f12011.
The make_unique function in util/memory.hh is not at all like
std::make_unique. The former is just a plain wrapper for the unique_ptr
constructor and makes the resulting unique_ptr take ownership of the
instance identified by the given pointer.
std::make_unique on the otherhand allocates a new instance of a given
type and makes creates a unique_ptr that has ownership of that instance.
So what the patch did was to allocate a char pointer, that did not
point at the string we're interested in, but instead points at the
pointer that points to that string. This means that the string that was
meant to be freed by the unique_ptr upon leaving its scope leaks.
Additionally, the check in open_selection() wasn't adapted to handle
the …
=> Revert "Use std::make_unique from c++14 #360"

config, man/termite.config.5, termite.cc
#245
Add a `bold_is_bright` option to correspond to [`vte_terminal_set_bold_is_bright`](https://github.com/GNOME/vte/commit/6c44229d130dd1d5cdb218e897ec6f245e96d538).
=> Add bold_is_bright option

README.rst, man/termite.1
This reverts commit db9eb18e97d1400a35515087aff2f5325b9779a7.
> Drop Ctrl-Shift-e shortcut
https://github.com/GNOME/gtk/blob/3.23.0/NEWS#L16
=> Revert "Document GTK's 'great' emoji input keybinding"
